#ifndef __RISCV_XT_H_
#define __RISCV_XT_H_

// clang-format off

#define INSN_CLASS_XUANTIE_LIST \
  INSN_CLASS_XTHEAD_START, \
  INSN_CLASS_XTHEADC, \
  INSN_CLASS_XTHEADE, \
  INSN_CLASS_XTHEADSE, \
  INSN_CLASS_XTHEADCBI, \
  INSN_CLASS_XTHEADCEI, \
  INSN_CLASS_XTHEADCF, \
  INSN_CLASS_XTHEADCV, \
  INSN_CLASS_XTHEADVSFA, \
  INSN_CLASS_XTHEADVSFB, \
  INSN_CLASS_XTHEADAIOE, \
  INSN_CLASS_XTHEADCBOP, \
  INSN_CLASS_XTHEADVARITH, \
  INSN_CLASS_XTHEAD_END, \


#endif